### PR TITLE
remove New and Init

### PR DESCRIPTION
**Pull request by rogpeppe**
As the zero value is OK to use, the New method is unnecessary.

Likewise, the Init method isn't necessary (`*d = deque.Deque{}` suffices).

Note that the existing Init method didn't actually clear all the fields (it didn't initialize lastTailPosition).

### CODE REVIEW

**Comment by christianrpetrin** [comment]
I agree there's really no need to have New and Init. Either using the deque zero value or the new keyword suffices. However, we'd love to get the deque into Go's std lib and so it's important for the deque to resemble the std lib container packages as much as possible. [list](https://github.com/golang/go/blob/master/src/container/list/list.go) and [ring](https://github.com/golang/go/blob/master/src/container/ring/ring.go), for instance, provide a New method. 

But mostly important, removing the New and Init would be a breaking change to the API. Although there's probably not many people using the deque right now, I want to make sure we follow the deque principles everywhere and at every step of the way. Breaking changes causes a lot of trouble for the users and it's our goal to treat the deque users like kings. They are the reason the deque exist and everything we do, should be aimed at making the deque users happier. Breaking changes is not a good way to start. :-)

Regarding the issue with Init not initializing lastTailPosition, I truly appreciate the insight and the recommendation to use "*d = deque.Deque{}" instead of clearing all fields one by one. I have commit this change [here](https://github.com/ef-ds/deque/commit/a8c39172dc15a8b366cf123eec9ffd245c2b816b) and it was released with v1.0.1.

**Comment by christianrpetrin** [comment]
I'll keep this PR open to collect feedback from other users. If you strongly feel like Init and New should be removed, please let us know. We love to get feedback and am very responsive and appreciative of them.

**Comment by rogpeppe** [comment]
With regard to API stability, the API hasn't been generally reviewed yet, so I think it's probably too early.
That said, you could always publish v2.

The list and ring packages require a New function because with neither of them is the zero value OK to use. Other types in the Go stdlib do not supply a New function unless it has an argument.

I don't know any examples of Init used as a method to zero a value. Reset is the usual standard, and that's used (for example by time.Timer) when we explicitly do *not* want to zero an object. I would support a Deque.Reset method that removed all items from the queue but kept around some allocated slices.

**Comment by christianrpetrin** [comment]
I agree it's probably too early to enforce API stability and it's definitely better to have a simpler API. Regarding the Deque.Reset suggestion, sounds very useful to me. I vote we do it. Feel free to get started with it. Otherwise let me know and I should be able to work on it this Friday (busy tomorrow). The changes looks good. 👍

**Comment by christianrpetrin** [comment]
We've been thinking about removing the Init and New methods and although these methods are really not required, they make using the deque a bit easier and cleaner. Using "d := deque.New()" not only looks better, but also saves a few keystrokes when compared to "d := new(deque.Deque)". Besides, we'll likely need a New method on the deque's safe for concurrent use future version, so both versions would be API compatible.

Also on top of that, it's a terrible inconvenience to have the users to perform code changes when they upgrade deque to a new version. Although apparently deque still has very few users right now given its infancy, even if a single user is using deque, that user deserves the MOST respect, and not the least. So I reverted the changes. We'll keep the API unchanged and won't do any breaking changes on this package. No v2 releases as well as this also requires code changes if the users want to upgrade to a v2 version.

This change have been reverted.

**Comment by rogpeppe** [comment]
> Using "d := deque.New()" not only looks better, but also saves a few keystrokes when compared to "d := new(deque.Deque)".

With other similar data structures, it's just as common to do:

    var d deque.Deque

which is just as nice IMHO. By including New *and* stating that the zero value is OK to use, you impose cognitive overhead because it's not entirely clear which is best to use.

> Besides, we'll likely need a New method on the deque's safe for concurrent use future version, so both versions would be API compatible.

None of Deque's anologs in the standard library are safe for concurrent use, so why should Deque itself become so? And why would you need a New method even in the concurrent-safe version, given that mutexes are OK to use when they're zero?

Also, note that it would be a breaking change to require New, given that you've stated that the zero value is OK to use.

One kind of New method that I'd consider fine is one that actually had an argument. For example, how about:

     // New returns a Deque instance pre-initialized with the given capacity.
     // Although the number of items in the queue may rise higher, there
     // will always be space available for at least cap items without allocation
     // even when there are no items in the queue.
     func New(cap int) *Deque

Second thing: you argued in favour of New, but why keep Init?

**Comment by christianrpetrin** [comment]
Excellent points! The idea of a New(cap) where deque would use a single, fixed size slice as its underlying data structure sounds useful. If the user knows for sure how many items they will push into the deque, deque could potentially perform a bit faster. The only problem with this change is the fact it would make deque not only a unbounded, but also a bounded data structure (according to how its used). I like the idea and I think its worth exploring as this seems to be a pretty common scenario (knowing the number of items beforehand).

In any case, there's no right or wrong answer whether New(with or without params) and Init should be there or not. Let's let deque's current and future users have a say about it. I'll file issues proposing both changes: Remove New and Init; Have New with a cap.

**Comment by rogpeppe** [comment]
> The idea of a New(cap) where deque would use a single, fixed size slice as its underlying data structure sounds useful.

To be honest, I wasn't thinking that it would make a single slice for all the elements, as that could have significant disadvantages if the size of the queue rises above the initial capacity and then drops again. I'd just allocate `(cap + (maxInternalSliceSize-1))/maxInternalSizeSize` nodes, each with maxInternalSliceSize capacity, and then just use them as normal. Then the queue would perform exactly as normal when the capacity rises above the initial capacity.

**Comment by christianrpetrin** [comment]
Sounds interesting. Can you please post an issue about it?

I created one to remove New and Init [here](https://github.com/ef-ds/deque/issues/7). Please leave your comments there (copy and paste from here).

**Comment by christianrpetrin** [comment]
Quick note: deque's future safe for concurrent use version will not be based on mutexes. Mutexes degrade performance a bit too dramatically. Deque's safe for concurrent use will use mixed techniques to achieve safe for concurrency use. I'm expecting much better performance when compared to using only mutexes.

**Pull request merged**
